Hack_Toolbox_Yggdrasil_version/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home_page'),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

dashboard/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'dashboard'

urlpatterns = [
        # dashboard views url
        path('', views.home_page, name='home_page'),
        path('external/', views.external, name='external'),
        path('nmap_visu/', views.nmap_visu, name='nmap_visu'),
        path('apropos/', views.apropos, name='apropos'),
        path('metasploit/', views.metasploit_visu, name='metasploit_visu'),
        path('crafter_exploit_port_based/', views.crafter_port_visu, name='crafter_port_visu'),
        path('crafter_exploit_dbdatabase_based/', views.crafter_version_visu, name='crafter_version_visu'),
        path('syn_flood_attack/', views.syn_flood_attack_visu, name='syn_flood_attack_visu'),
        path('blackhat_script_attack/', views.blackhat_attack_visu, name='blackhat_attack_visu')
        ]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms


class Input_for_Test(forms.Form):
    test_str = forms.CharField(max_length=15, required=False, label=False,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='test_str'


class Formulaire_entree(forms.Form):
    entry_str = forms.CharField(max_length=15, required=False, label=False,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'entry_str'}))  # label='entry_str'


class Formulaire_entree_search_metasploit(forms.Form):
    search_str = forms.CharField(max_length=30, required=False, label=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control col'}))  # label='search_str'


class Formulaire_entree_run_metasploit(forms.Form):
    run_str = forms.CharField(max_length=70, required=False, label=False,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='run_str'


class Formulaire_entree_options_metasploit(forms.Form):
    option_str = forms.CharField(max_length=30, required=False, label=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='option_str'


class Formulaire_entree_options_arg_metasploit(forms.Form):
    option_arg_str = forms.CharField(max_length=70, required=False, label=False,
                                     widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='option_arg_str'


class Formulaire_entree_payload_metasploit(forms.Form):
    payload_str = forms.CharField(max_length=70, required=False, label=False,
                                  widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='payload_str'


class Formulaire_entree_payload_option_metasploit(forms.Form):
    payload_option_str = forms.CharField(max_length=70, required=False, label=False,
                                         widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='payload_str'


class Formulaire_entree_payload_option_val_metasploit(forms.Form):
    payload_option_value_str = forms.CharField(max_length=70, required=False, label=False,
                                               widget=forms.TextInput(
                                                   attrs={'class': 'form-control'}))  # label='payload_str'


class Formulaire_entree_prompt_metasploit(forms.Form):
    prompt_str = forms.CharField(max_length=80, required=False, label=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='payload_str'


# radio_select widget

class Selection_entree(forms.Form):
    SCAN_CHOICES = (
        ('TCP', 'TCP'),
        ('SYN', 'SYN'),
        ('UDP', 'UDP'),
        ('VERSION', 'VERSION'),
    )

    scan_wanted = forms.ChoiceField(choices=SCAN_CHOICES, label=False,
                                    widget=forms.RadioSelect(attrs={'class': 'list-unstyled', 'id': 'scan_wanted'}), required=True)


class Type_var_metasploit(forms.Form):
    SCAN_CHOICES = (
        ('INT', 'INT'),
        ('BOOL', 'BOOL'),
        ('STR', 'STR')
    )

    type_wanted = forms.ChoiceField(choices=SCAN_CHOICES, label=False,
                                    widget=forms.RadioSelect(attrs={'class': 'list-unstyled'}),
                                    required=False)


class Type_var_payload_metasploit(forms.Form):
    SCAN_CHOICES = (
        ('INT', 'INT'),
        ('BOOL', 'BOOL'),
        ('STR', 'STR')
    )

    type_payload_wanted = forms.ChoiceField(choices=SCAN_CHOICES, label=False,
                                            widget=forms.RadioSelect(attrs={'class': 'list-unstyled'}),
                                            required=False)


class Choice_module(forms.Form):
    MODULES_CHOICES = (
        ('EXPLOIT', 'EXPLOIT'),
        ('AUXILIARY', 'AUXILIARY')
    )

    module_wanted = forms.ChoiceField(choices=MODULES_CHOICES, label=False,
                                      widget=forms.RadioSelect(attrs={'class': 'list-unstyled'}),
                                      required=True)


class Checkbox_args_entree(forms.Form):
    ARGUMENTS = (
        ('v4', 'IPv4'),
        ('p-', 'Scan forced on all ports (1-65535)'),
        ('Pn', 'Skip host discovery')
    )

    arguments_checkbox = forms.MultipleChoiceField(choices=ARGUMENTS, label=False,
                                                   widget=forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled',
                                                                                              'id': 'arguments_checkbox'}),
                                                   required=False)



class IP_cible_entree(forms.Form):
    ip_flood_syn_target = forms.CharField(max_length=15, required=False, label=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='entry_str'

class Port_de_la_cible(forms.Form):
    port_flood_syn_target = forms.CharField(max_length=15, required=False, label=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='entry_str'

class Nombre_de_paquet(forms.Form):
    paquet_flood_syn_target = forms.CharField(max_length=15, required=False, label=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))  # label='entry_str'

dashboard/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_control
from .forms import Input_for_Test, Formulaire_entree, Selection_entree, Checkbox_args_entree, \
    Formulaire_entree_search_metasploit, Formulaire_entree_run_metasploit, Formulaire_entree_options_metasploit, \
    Formulaire_entree_options_arg_metasploit, Formulaire_entree_payload_metasploit, Type_var_metasploit, \
    Formulaire_entree_prompt_metasploit, Type_var_payload_metasploit, Formulaire_entree_payload_option_metasploit, \
    Formulaire_entree_payload_option_val_metasploit, Choice_module, IP_cible_entree, Port_de_la_cible, Nombre_de_paquet

import sys
import os
import time

import pdb

# add executables' folder path
ProjectFileDir = os.path.dirname(os.path.abspath(__file__))
DashboardScriptDir = os.path.join(ProjectFileDir, 'static/script/')
sys.path.append(DashboardScriptDir)

from metasploit_script import Msfrpc


# Create your views here.

def home_page(request):
    '''

    @param request: request made by the user on the web page
    @return: the view for the home page
    '''
    from extra_scripts import setup_shell
    setup_shell()
    time.sleep(3)
    return render(request, 'dashboard/home/home.html', {})


def apropos(request):
    '''

    @param request: request made by the user on the web page
    @return: the view for the about page
    '''
    return render(request, 'dashboard/home/apropos.html', {})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)  # flush the cache page
def external(request):
    '''

    @param request: request made by the user on the web page
    @return: the view for the test's module
    '''
    form = Input_for_Test(request.POST)

    if form.is_valid():

        if request.method == 'POST' and 'run_script' in request.POST:
            # import function to run
            from test_script import main

            inp = request.POST.get('test_str')
            # test section
            # print(inp)

            # call function
            data = main(inp)

            # renderer
            return render(request, 'dashboard/home/test.html', {'form': form, 'data': data})

    return render(request, 'dashboard/home/test.html', {'form': form})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def nmap_visu(request):
    '''

    @param request: request made by the user on the web page
    @return: the view for the nmap's module
    '''
    # save data module
    global data_nmap
    import pickle

    type_scan = Selection_entree(request.POST)
    ip_cible = Formulaire_entree(request.POST)
    arguments = Checkbox_args_entree(request.POST)

    if type_scan.is_valid() and ip_cible.is_valid() and arguments.is_valid() and request.method == 'POST' and 'run_script' in request.POST:

        if request.method == 'POST' and 'run_script' in request.POST:
            # import function to run
            from nmap_script import main
            from pass_crypt import crypted_json

            type_scan_val = request.POST.get('scan_wanted')
            ip_cible_val = request.POST.get('entry_str')
            arguments_val = request.POST.getlist('arguments_checkbox')

            # test section
            # print(type_scan_val)
            # print(ip_cible_val)
            # print(arguments_val)

            # call function
            data = main(type_scan_val, ip_cible_val, arguments_val)

            # delete useless data (!!!!!!!!!!!!!!!!!!!!!!!!CHANGE JSON TREATMENT !!!!!!!!!!!!!!!!!!)
            del data['stats']
            del data['runtime']
            data_nmap = data

            # Store data (serialize)
            with open('dashboard/static/.transit/filename.pickle', 'wb') as handle:
                pickle.dump(crypted_json(data_nmap), handle, protocol=pickle.HIGHEST_PROTOCOL)

            # renderer
            return render(request, 'dashboard/home/nmap_console.html',
                          {'type_scan_val': type_scan_val, 'ip_cible_val': ip_cible_val, 'arguments_val': arguments_val,
                           'data': data})

    return render(request, 'dashboard/home/nmap_console.html',
                  {'type_scan': type_scan, 'ip_cible': ip_cible, 'arguments': arguments})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def metasploit_visu(request):
    '''

    @param request: request made by the user on the web page
    @return: the metasploit's module
    '''

    # creation of flag
    global flag_connection
    global flag_search
    global flag_run
    global flag_option
    global flag_payload
    global flag_error
    global flag_auxiliary_ready_to_run
    global flag_choice
    global flag_payload_value

    # global var
    global module_choice
    global session
    global status_connection
    global env

    # global form
    global list_of_module
    global new_list
    global module_run
    global module_description
    global module_options
    global module_missing_required
    global module_running_config
    global module_targetpayload
    global payload_chosen
    global payload_runoptions
    global payload_runoptions_save
    global payload_missing_required
    global json_payload
    data = None

    champ_de_recherche = Formulaire_entree_search_metasploit(request.POST)
    champ_du_run = Formulaire_entree_run_metasploit(request.POST)
    champ_de_l_option = Formulaire_entree_options_metasploit(request.POST)
    champ_de_l_arg_de_option = Formulaire_entree_options_arg_metasploit(request.POST)
    champ_du_payload = Formulaire_entree_payload_metasploit(request.POST)
    champ_de_la_config_payload = Formulaire_entree_payload_option_metasploit(request.POST)
    champ_de_la_val_de_la_config_payload = Formulaire_entree_payload_option_val_metasploit(request.POST)

    type_module = Choice_module(request.POST)
    type_de_var = Type_var_metasploit(request.POST)
    type_de_var_payload = Type_var_payload_metasploit(request.POST)

    champ_du_prompt = Formulaire_entree_prompt_metasploit(request.POST)

    #############################CONNECTION RPC CLIENT ################################
    if request.method == 'POST' and 'run_script' in request.POST:

        # initiate environement
        env = Msfrpc()

        # call function
        env.launch_metasploit()
        env.connection_rpc()

        if env.client is not None:
            flag_connection = "connected"
            status_connection = "connected"

        # retry
        else:
            env.launch_metasploit()
            time.sleep(5)
            env.connection_rpc()

        if env.client is None:
            flag_connection = None
            status_connection = "échec"

        else:
            flag_connection = "connected"
            status_connection = "connected"

        # renderer
        return render(request, 'dashboard/home/metasploit_console.html',
                      {'flag_connection': flag_connection, 'champ_de_recherche': champ_de_recherche,
                       'type_module': type_module, 'status_connection': status_connection})

    ##############################PRE-SELECTION MODULE'S TYPE ###############################
    if request.method == 'POST' and 'run_display_module' in request.POST:

        # checked pseudo~~~flag
        flag_choice = "True"
        # test section

        # call function
        module_choice = request.POST.get('module_wanted')

        # print(module_choice)

        if module_choice == "EXPLOIT":

            env.get_exploits()
            list_of_module = env.list_of_exploit

        elif module_choice == "AUXILIARY":

            env.get_auxiliaries()
            list_of_module = env.list_of_auxiliaries

        # renderer
        return render(request, 'dashboard/home/metasploit_console.html',
                      {'flag_connection': flag_connection, 'list_of_module': list_of_module,
                       'champ_de_recherche': champ_de_recherche, 'type_module': type_module,
                       'flag_choice': flag_choice, 'status_connection': status_connection})

    #################################SELECTION OF ATTACK'S MOODULE###################
    if champ_de_recherche.is_valid() and request.method == 'POST' and 'run_search' in request.POST:

        ######################################EXPLOIT SECTION####################################
        if module_choice == "EXPLOIT":

            word_wanted = request.POST.get('search_str')

            # checked pseudo~~~flag
            flag_search = "True"

            # test section

            # call function
            env.get_exploits()
            list_of_exploit = env.list_of_exploit

            # create new list
            new_list = []

            for i in range(0, len(list_of_exploit), 1):

                if word_wanted in list_of_exploit[i]:
                    new_list.append(list_of_exploit[i])

            # render
            return render(request, 'dashboard/home/metasploit_console.html',
                          {'flag_connection': flag_connection, 'new_list': new_list,
                           'champ_de_recherche': champ_de_recherche, 'flag_search': flag_search,
                           'champ_du_run': champ_du_run, 'type_module': type_module,
                           'flag_choice': flag_choice, 'status_connection': status_connection})

        ######################################AUXILIARY SECTION##################################
        elif module_choice == "AUXILIARY":

            word_wanted = request.POST.get('search_str')

            # checked pseudo~~~flag
            flag_search = "True"

            # test section

            # call function
            env.get_auxiliaries()
            list_of_auxiliary = env.list_of_auxiliaries

            # create new list
            new_list = []

            for i in range(0, len(list_of_auxiliary), 1):

                if word_wanted in list_of_auxiliary[i]:
                    new_list.append(list_of_auxiliary[i])

dashboard/templates/dashboard/home/apropos.html
{% extends "dashboard/base.html" %}
{% block title %}A propos{% endblock title %}

<!-- Soon this project will be reshape in CWP (Cipher Wyrm Privacy -->


{% block content %}  

{# À propos section #} 

<div class="mt-5 py-2 p-3  ">
        <h1 class="border-bottom" style="max-width: 30%">À propos</h1>
        <p class="py-2">Hacktool Box est un outil web-graphique visant à faciliter l'utilisation des programmes de pentest les plus courant. Le github associé à ce projet se trouve au lien suivant : <a href="https://github.com/Andaris777/Hack_Toolbox-project">github_hack_toolbox</a>
        </p>
</div>



{% endblock content %}

dashboard/templates/dashboard/home/blackhat_attack_console.html
{% extends "dashboard/base.html" %}
{% load extras_filter %}
{% block title %}Black Hat Attack (Nmap + Msf){% endblock title %}


{% block content %}

    <div class="row">

        <div class="col">
            <div class="mt-5 py-2 p-3">
                <h1 class="border-bottom" style="max-width: 40%">Présentation</h1>
                <p class="py-2">Ce module couple Nmap à Metasploit et ceux, dans le but de générer automatique des sessions (shell ou meterpreter)</p>
                <p class="py-2">En ce sens, lancez au préalable Nmap avant de lancer ce module si ce n'est pas déjà fait : <a href="{% url 'dashboard:nmap_visu' %}">Nmap</a></p>
                <p class="py-2">Pour lancer le scan du dit module, veuillez cliquer sur le bouton ci-dessous : </p>
                <form method="post" class="form-group text-left">
                    {% csrf_token %}
                    <button type="submit" name="run_blackhat_script" class="btn btn-primary btn-lg" id="runbutton">Run Black Hat Script</button>
                </form>
                <p class="py-2">Attention, ce module peut-être particulièrement chronophage.</p>
            </div>
        </div>

        <div class="col">
<!--            <div class="d-flex justify-content-center m-5">-->
<!--              <div class="spinner-grow text-primary" style="width: 5rem; height: 5rem;" role="status">-->
<!--                <span class="sr-only p-5 m-5">Loading...</span>-->
<!--              </div>-->
<!--            </div>-->
            {% if flag_launch_blackhat_attack_script %}
                <div class="mt-5 py-2 p-3">
                    <h1 class="border-bottom" style="max-width:50%">Résultat du scan</h1>
                    <div class="overflow-auto" style="max-width: 80%; max-height: 500px;">
                        <table class="table">
                            {% for id, dict_of_session in sessions_list.items %}
                                <thead>
                                        <tr>
                                                <th class="h2">Target : {{dict_of_session|get_item:"target_host"}}</th>
                                        </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td class="h3">Remote port : {{dict_of_session|get_item:"session_port"}}</td>
                                        </tr>
                                        <tr>
                                            <td class="h3">Exploit : {{dict_of_session|get_item:"via_exploit"}}</td>
                                        </tr>
                                        <tr>
                                            <td class="h3">Payload : {{dict_of_session|get_item:"via_payload"}}</td>
                                        </tr>
                                        <tr>
                                            <td class="h3">Type de console : {{dict_of_session|get_item:"type"}}</td>
                                        </tr>
                                        <tr>
                                            <td class="h3">Architecture : {{dict_of_session|get_item:"arch"}}</td>
                                        </tr>
                                </tbody>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            {% else %}
                <div class="d-flex justify-content-center m-5">
                  <div class="spinner-grow text-primary" style="width: 5rem; height: 5rem;" role="status" id="spinner" hidden>
                    <span class="sr-only p-5 m-5">Loading...</span>
                  </div>
                </div>
            {% endif %}
        </div>

    </div>

    <script type="text/javascript">
        $("#runbutton").on('click', function() {
            $("#spinner").removeAttr('hidden')
        });

	</script>

{% endblock content %}

dashboard/templates/dashboard/home/home.html
{% extends "dashboard/base.html" %}
{% block title %}Hack tools{% endblock title %}


{% block content %}
<div>
    <div class="mt-5 text-center ">
        <main class="inner cover" role="main">
            <h1 class="cover-heading "> Hack Toolbox </h1>
        </main>
    </div>
    <div class="mt-5 text-center ">
        <h2> Bienvenue dans l'outils Hack Toolbox </h2>
        <p class="py-2"> Cette interface a été développée dans le but de faciliter l'utilisation des outils les plus courants dans le domaine du pentesting</p>
    </div>
</div>



{% endblock content %}

dashboard/templates/dashboard/home/metasploit_console_prompt.html
{% extends "dashboard/base.html" %}
{% block title %}Metasploit prompt{% endblock title %}


{% block content %}
<form method="post" class="form-group text-left">
    <div class="mt-5 py-2 p-3">
        <h1 class="border-bottom" style="max-width: 40%">Prompt de la console</h1>
    </div>
    <div class="bg-primary bg-gradient rounded-3 p-3" style="max-width: 40%">
        <p class="py-2">Indiquer le commande à rentrer</p>
        <div class="mt-2 py-2">
            {% csrf_token %}
            {{champ_du_prompt}}
        </div>
    </div>
    <div class="mt-5 py-2 p-3">
        <button type="submit" name="run_cmd" class="btn btn-primary btn-lg mt-2">Run Command</button>
    </div>
</form>

<div>
    <div class="mt-5 py-2 p-3">
        <h1 class="border-bottom" style="max-width: 40%">Output de la console</h1>
    </div>
    <div class="overflow-auto border border-dark p-3 list-unstyled mt-2" style="max-width: 60%; max-height: 500px;">
        <pre>{{ output }}</pre>
    </div>
</div>

{% endblock content %}

dashboard/templates/dashboard/home/syn_flood_console.html
{% extends "dashboard/base.html" %}
{% block title %}SYN flood console{% endblock title %}

{% block javascript %}
{% endblock %}

{% block content %}

{# À propos section #}
<div class="py-2 p-3">
        <form method="post" class="form-group text-left">

            <div class="mt-5 py-2 p-3"  style="max-width: 30%">
                <h1 class=" border-bottom">Adresse IP de la cible</h1>
            </div>
            <div class="mt-2 py-2 p-3 bg-primary bg-gradient rounded-3" style="max-width: 30%">
                <!--	<input type=“text“ name=“param“> -->
                <p class="py-2">Entrer l'adresse IP de la cible</p>
                 {{ip_de_la_cible}}
            </div>

            <div class="mt-5 py-2 p-3"  style="max-width: 30%">
                <h1 class=" border-bottom">Numéro de port de la cible</h1>
            </div>
            <div class="mt-2 py-2 p-3 bg-primary bg-gradient rounded-3" style="max-width: 30%">
                <p class="py-2">Entrer le numéro de port de la cible</p>
                {{port_de_la_cible}}
            </div>

            <div class="mt-5 py-2 p-3"  style="max-width: 30%">
                 <h1 class="border-bottom">Nombre de paquets à envoyer à la cible</h1>
            </div>
            <div class="mt-2 py-2 p-3 bg-primary bg-gradient rounded-3" style="max-width: 30%">
                 <p class="py-2">Entrez le nombre de paquets à envoyer à la cible</p>
                 {{nombre_de_paquet}}
            </div>

            <div class="mt-5 py-2 p-3">
		    {% csrf_token %}
		    <button type="submit" name="run_script" class="btn btn-primary btn-lg">Run script</button>
		    </div>
        </form>
</div>

<div class="mt-5 py-2 p-3">
    <h1 class="border-bottom" style="max-width: 30%">Options choisies</h1>
    <table class="table" style="max-width: 30%">
        <tbody>
        <tr><td>IP choisie</td><td id = "ip_choosen">None</td></tr>
        <tr><td>Numéro de port choisi</td><td id = "port_choosen">None</td></tr>
        <tr><td>Nombre de paquet choisi</td><td id = "number_packet_choosen">None</td></tr>
        </tbody>
    </table>
</div>

<div class="mt-5 py-2 p-3">
    <h1 class=" border-bottom">Message</h1>
    <p class="py-2">{{message}}</p>
</div>


<!--jquery-->
<script type="text/javascript">
//when page is loaded
	$(document).ready(function() {
		//update function for IP address
		$("#id_ip_flood_syn_target").on('keyup', function() {
			$("#ip_choosen").html($(this).val());
		});
		//update function for port target
		$("#id_port_flood_syn_target").on('keyup', function() {
			$("#port_choosen").html($(this).val());
		});
		//update function for number of packets
		$("#id_paquet_flood_syn_target").on('keyup', function() {
			$("#number_packet_choosen").html($(this).val());
		});
	});
</script>

{% endblock content %}

dashboard/templates/dashboard/home/test.html
{% extends "dashboard/base.html" %}
{% block title %}Python button script{% endblock title %}


{% block content %}  

	<form method="post" class="form-group text-left">

		<div class="mt-5 py-2 p-3">
			<h1 class="border-bottom">Input Text</h1>
		</div>
		<div class="py-2 p-3 bg-primary bg-gradient rounded-3" style="max-width: 30%">
			<p class="py-2">Entrez du texte</p>
			{% csrf_token %}
			{{form}}
		</div>


		<div class="mt-5 py-2 p-3">
			{% csrf_token %}
			<button type="submit" name="run_script" class="btn btn-primary btn-lg">Run script</button>
		</div>
	</form>
	<div class="mt-5 py-2 p-3">
		<h1>The answer</h1>
	</div>
	<div class=" mt-2 py-2 border border-dark p-3" style="max-width: 30%">
		{{data}}
	</div>
	</div>

{% endblock content %}